// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckzclithmxtixaykrava.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNremNsaXRobXh0aXhheWtyYXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzkwMDAsImV4cCI6MjA2MjExNTAwMH0.0SO-ttFnNquFihbWZcv7JB8zsCAXYPpfLvs0MPaunsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);